controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true  # Fixed typo: was "use_sime_time"

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    position_controller:
      type: position_controllers/JointGroupPositionController
    
    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
    
    effort_controller:
      type: effort_controllers/JointGroupEffortController
    
    joint_trajectory_controller:
      type: "joint_trajectory_controller/JointTrajectoryController"


joint_state_broadcaster:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    interfaces:
      - position
      - velocity
    publish_rate: 100.0


position_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    interface_name: position


velocity_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    interface_name: velocity


effort_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
    interface_name: effort


joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6

    command_interfaces:
      - position
      
    state_interfaces:
      - position
      - velocity

    state_publish_rate: 100.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    open_loop_control: false  # Changed to false for better control
    allow_integration_in_goal_trajectories: true  # Added for smoother trajectories
    
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.5  # Allow some tolerance for goal achievement
      # Per-joint constraints
      joint_1:
        trajectory: 0.1  # Increased tolerance for trajectory following
        goal: 0.05       # Increased tolerance for goal achievement
      joint_2:
        trajectory: 0.1
        goal: 0.05
      joint_3:
        trajectory: 0.1
        goal: 0.05
      joint_4:
        trajectory: 0.1
        goal: 0.05
      joint_5:
        trajectory: 0.1
        goal: 0.05
      joint_6:
        trajectory: 0.1
        goal: 0.05
